In [12]:
import hashlib
import numpy as np
from datasets import get_dataset

In [47]:
def hash_frame(frame):
    byte_data = frame.tobytes()
    
    # 使用SHA-256哈希函数
    hash_obj = hashlib.sha256(byte_data)
    hash_digest = hash_obj.digest()
    
    # 如果哈希结果不足需要的长度，重复哈希结果直到长度足够
    hash_data = bytearray()
    while len(hash_data) < frame.size:  # frame.size是像素的数量
        hash_data.extend(hash_digest)
        hash_obj.update(hash_digest)
        hash_digest = hash_obj.digest()
    
    # 截取所需长度并将字节序列转换为整数数组
    hash_data = hash_data[:frame.size]
    hashed_frame = np.frombuffer(hash_data, dtype=np.uint8).reshape(frame.shape)
    # print(hashed_frame)

    return hashed_frame

def create_static_trigger(pos, data, size_width, size_height, width, height):
        
        if pos == 'top-left':
            x_begin = 0
            x_end = size_width
            y_begin = 0
            y_end = size_height

        elif pos == 'top-right':
            x_begin = int(width - size_width)
            x_end = width
            y_begin = 0
            y_end = size_height

        elif pos == 'bottom-left':
            x_begin = 0
            x_end = size_width
            y_begin = int(height - size_height)
            y_end = height

        elif pos == 'bottom-right':
            x_begin = int(width - size_width)
            x_end = width
            y_begin = int(height - size_height)
            y_end = height

        elif pos == 'middle':
            x_begin = int((width - size_width) / 2)
            x_end = int((width + size_width) / 2)
            y_begin = int((height - size_height) / 2)
            y_end = int((height + size_height) / 2)

        elif pos == 'random':
            x_begin = np.random.randint(0, int(width - size_width))
            x_end = x_begin + size_width
            y_begin = np.random.randint(0, int(height - size_height))
            y_end = y_begin + size_height

        # The shape of the data is (N, T, C, H, W)
        T, C, H, W = data.shape

        # for n in range(N):
        for t in range(T):
            for c in range(C):
                frame = data[t, c, y_begin:y_end, x_begin:x_end]
                hashed_frame = hash_frame(frame)
                # Normalize hashed_frame to binary (0 or 1) values
                # binary_frame = (hashed_frame % 4).astype(np.uint8)
                # for x in range(binary_frame.shape[0]):
                #     for y in range(binary_frame.shape[1]):
                #         polarity = binary_frame[x][y]
                #         if polarity == 0:
                #             data[ t, :, y_begin+y, x_begin+x] = 0
                #         elif polarity == 1:
                #             data[ t, 0, y_begin+y, x_begin+x] = 0
                #             data[ t, 1, y_begin+y, x_begin+x] = 1
                #         elif polarity == 2:
                #             data[ t, 0, y_begin+y, x_begin+x] = 1
                #             data[ t, 1, y_begin+y, x_begin+x] = 0
                #         else:
                #             data[ :, :, y_begin+y, x_begin+x] = 1
                            
                binary_frame = (hashed_frame % 2).astype(np.uint8)
                print(binary_frame)

                data[t, c, y_begin:y_end, x_begin:x_end] = binary_frame
              
        return data

In [49]:
from spikingjelly.datasets.n_mnist import NMNIST
data = NMNIST('data/mnist', train=True, data_type='frame',
                           split_by='number', frames_number=16)
from spikingjelly.datasets import play_frame
one = (data[0][0])
width, height = one.shape[2:]

trigger_size = 0.1

size_width = int(trigger_size * width)
size_height = int(trigger_size * height)


if size_width == 0:
    size_width = 1
    size_height = 1
    
# print(size_height)
two = create_static_trigger('top-left', one, size_width, size_height, width, height)
# print(one.shape)
play_frame(two,'123.gif')

The directory [data/mnist/frames_number_16_split_by_number] already exists.
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 1 0]
 [0 1 1]
 [0 0 1]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
[[1 0 1]
 [1 1 1]
 [0 0 0]]
Save frames to [123.gif].
